//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MonsterMessages.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMonsterMessagesListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MonsterMessagesBaseListener : IMonsterMessagesListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r34"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR34([NotNull] MonsterMessagesParser.R34Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r34"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR34([NotNull] MonsterMessagesParser.R34Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r42"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR42([NotNull] MonsterMessagesParser.R42Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r42"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR42([NotNull] MonsterMessagesParser.R42Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r115"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR115([NotNull] MonsterMessagesParser.R115Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r115"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR115([NotNull] MonsterMessagesParser.R115Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r106"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR106([NotNull] MonsterMessagesParser.R106Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r106"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR106([NotNull] MonsterMessagesParser.R106Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r71"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR71([NotNull] MonsterMessagesParser.R71Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r71"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR71([NotNull] MonsterMessagesParser.R71Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r56"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR56([NotNull] MonsterMessagesParser.R56Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r56"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR56([NotNull] MonsterMessagesParser.R56Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r10"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR10([NotNull] MonsterMessagesParser.R10Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r10"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR10([NotNull] MonsterMessagesParser.R10Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r46"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR46([NotNull] MonsterMessagesParser.R46Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r46"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR46([NotNull] MonsterMessagesParser.R46Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r20"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR20([NotNull] MonsterMessagesParser.R20Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r20"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR20([NotNull] MonsterMessagesParser.R20Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r67"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR67([NotNull] MonsterMessagesParser.R67Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r67"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR67([NotNull] MonsterMessagesParser.R67Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r78"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR78([NotNull] MonsterMessagesParser.R78Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r78"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR78([NotNull] MonsterMessagesParser.R78Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r25"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR25([NotNull] MonsterMessagesParser.R25Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r25"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR25([NotNull] MonsterMessagesParser.R25Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r74"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR74([NotNull] MonsterMessagesParser.R74Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r74"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR74([NotNull] MonsterMessagesParser.R74Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r103"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR103([NotNull] MonsterMessagesParser.R103Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r103"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR103([NotNull] MonsterMessagesParser.R103Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r94"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR94([NotNull] MonsterMessagesParser.R94Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r94"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR94([NotNull] MonsterMessagesParser.R94Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r116"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR116([NotNull] MonsterMessagesParser.R116Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r116"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR116([NotNull] MonsterMessagesParser.R116Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r60"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR60([NotNull] MonsterMessagesParser.R60Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r60"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR60([NotNull] MonsterMessagesParser.R60Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR0([NotNull] MonsterMessagesParser.R0Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR0([NotNull] MonsterMessagesParser.R0Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r110"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR110([NotNull] MonsterMessagesParser.R110Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r110"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR110([NotNull] MonsterMessagesParser.R110Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r55"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR55([NotNull] MonsterMessagesParser.R55Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r55"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR55([NotNull] MonsterMessagesParser.R55Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r100"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR100([NotNull] MonsterMessagesParser.R100Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r100"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR100([NotNull] MonsterMessagesParser.R100Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r58"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR58([NotNull] MonsterMessagesParser.R58Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r58"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR58([NotNull] MonsterMessagesParser.R58Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r61"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR61([NotNull] MonsterMessagesParser.R61Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r61"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR61([NotNull] MonsterMessagesParser.R61Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r84"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR84([NotNull] MonsterMessagesParser.R84Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r84"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR84([NotNull] MonsterMessagesParser.R84Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r65"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR65([NotNull] MonsterMessagesParser.R65Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r65"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR65([NotNull] MonsterMessagesParser.R65Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r5"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR5([NotNull] MonsterMessagesParser.R5Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r5"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR5([NotNull] MonsterMessagesParser.R5Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r112"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR112([NotNull] MonsterMessagesParser.R112Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r112"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR112([NotNull] MonsterMessagesParser.R112Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r99"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR99([NotNull] MonsterMessagesParser.R99Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r99"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR99([NotNull] MonsterMessagesParser.R99Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r39"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR39([NotNull] MonsterMessagesParser.R39Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r39"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR39([NotNull] MonsterMessagesParser.R39Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r52"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR52([NotNull] MonsterMessagesParser.R52Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r52"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR52([NotNull] MonsterMessagesParser.R52Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r47"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR47([NotNull] MonsterMessagesParser.R47Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r47"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR47([NotNull] MonsterMessagesParser.R47Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r31"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR31([NotNull] MonsterMessagesParser.R31Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r31"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR31([NotNull] MonsterMessagesParser.R31Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR4([NotNull] MonsterMessagesParser.R4Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR4([NotNull] MonsterMessagesParser.R4Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r53"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR53([NotNull] MonsterMessagesParser.R53Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r53"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR53([NotNull] MonsterMessagesParser.R53Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r124"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR124([NotNull] MonsterMessagesParser.R124Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r124"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR124([NotNull] MonsterMessagesParser.R124Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r48"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR48([NotNull] MonsterMessagesParser.R48Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r48"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR48([NotNull] MonsterMessagesParser.R48Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r123"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR123([NotNull] MonsterMessagesParser.R123Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r123"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR123([NotNull] MonsterMessagesParser.R123Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r26"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR26([NotNull] MonsterMessagesParser.R26Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r26"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR26([NotNull] MonsterMessagesParser.R26Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r51"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR51([NotNull] MonsterMessagesParser.R51Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r51"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR51([NotNull] MonsterMessagesParser.R51Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r6"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR6([NotNull] MonsterMessagesParser.R6Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r6"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR6([NotNull] MonsterMessagesParser.R6Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r122"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR122([NotNull] MonsterMessagesParser.R122Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r122"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR122([NotNull] MonsterMessagesParser.R122Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r93"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR93([NotNull] MonsterMessagesParser.R93Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r93"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR93([NotNull] MonsterMessagesParser.R93Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r37"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR37([NotNull] MonsterMessagesParser.R37Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r37"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR37([NotNull] MonsterMessagesParser.R37Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r44"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR44([NotNull] MonsterMessagesParser.R44Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r44"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR44([NotNull] MonsterMessagesParser.R44Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r12"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR12([NotNull] MonsterMessagesParser.R12Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r12"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR12([NotNull] MonsterMessagesParser.R12Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r45"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR45([NotNull] MonsterMessagesParser.R45Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r45"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR45([NotNull] MonsterMessagesParser.R45Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r19"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR19([NotNull] MonsterMessagesParser.R19Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r19"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR19([NotNull] MonsterMessagesParser.R19Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r33"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR33([NotNull] MonsterMessagesParser.R33Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r33"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR33([NotNull] MonsterMessagesParser.R33Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r108"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR108([NotNull] MonsterMessagesParser.R108Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r108"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR108([NotNull] MonsterMessagesParser.R108Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r95"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR95([NotNull] MonsterMessagesParser.R95Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r95"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR95([NotNull] MonsterMessagesParser.R95Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r82"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR82([NotNull] MonsterMessagesParser.R82Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r82"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR82([NotNull] MonsterMessagesParser.R82Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r69"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR69([NotNull] MonsterMessagesParser.R69Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r69"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR69([NotNull] MonsterMessagesParser.R69Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r104"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR104([NotNull] MonsterMessagesParser.R104Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r104"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR104([NotNull] MonsterMessagesParser.R104Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r35"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR35([NotNull] MonsterMessagesParser.R35Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r35"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR35([NotNull] MonsterMessagesParser.R35Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r32"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR32([NotNull] MonsterMessagesParser.R32Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r32"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR32([NotNull] MonsterMessagesParser.R32Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r27"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR27([NotNull] MonsterMessagesParser.R27Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r27"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR27([NotNull] MonsterMessagesParser.R27Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r40"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR40([NotNull] MonsterMessagesParser.R40Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r40"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR40([NotNull] MonsterMessagesParser.R40Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r66"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR66([NotNull] MonsterMessagesParser.R66Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r66"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR66([NotNull] MonsterMessagesParser.R66Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r101"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR101([NotNull] MonsterMessagesParser.R101Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r101"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR101([NotNull] MonsterMessagesParser.R101Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r109"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR109([NotNull] MonsterMessagesParser.R109Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r109"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR109([NotNull] MonsterMessagesParser.R109Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r80"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR80([NotNull] MonsterMessagesParser.R80Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r80"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR80([NotNull] MonsterMessagesParser.R80Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r83"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR83([NotNull] MonsterMessagesParser.R83Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r83"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR83([NotNull] MonsterMessagesParser.R83Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r64"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR64([NotNull] MonsterMessagesParser.R64Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r64"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR64([NotNull] MonsterMessagesParser.R64Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r30"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR30([NotNull] MonsterMessagesParser.R30Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r30"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR30([NotNull] MonsterMessagesParser.R30Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r17"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR17([NotNull] MonsterMessagesParser.R17Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r17"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR17([NotNull] MonsterMessagesParser.R17Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r86"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR86([NotNull] MonsterMessagesParser.R86Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r86"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR86([NotNull] MonsterMessagesParser.R86Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r15"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR15([NotNull] MonsterMessagesParser.R15Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r15"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR15([NotNull] MonsterMessagesParser.R15Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r24"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR24([NotNull] MonsterMessagesParser.R24Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r24"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR24([NotNull] MonsterMessagesParser.R24Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r11"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR11([NotNull] MonsterMessagesParser.R11Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r11"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR11([NotNull] MonsterMessagesParser.R11Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r118"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR118([NotNull] MonsterMessagesParser.R118Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r118"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR118([NotNull] MonsterMessagesParser.R118Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r98"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR98([NotNull] MonsterMessagesParser.R98Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r98"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR98([NotNull] MonsterMessagesParser.R98Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r16"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR16([NotNull] MonsterMessagesParser.R16Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r16"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR16([NotNull] MonsterMessagesParser.R16Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r89"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR89([NotNull] MonsterMessagesParser.R89Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r89"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR89([NotNull] MonsterMessagesParser.R89Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r113"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR113([NotNull] MonsterMessagesParser.R113Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r113"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR113([NotNull] MonsterMessagesParser.R113Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r126"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR126([NotNull] MonsterMessagesParser.R126Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r126"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR126([NotNull] MonsterMessagesParser.R126Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r68"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR68([NotNull] MonsterMessagesParser.R68Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r68"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR68([NotNull] MonsterMessagesParser.R68Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r79"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR79([NotNull] MonsterMessagesParser.R79Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r79"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR79([NotNull] MonsterMessagesParser.R79Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r91"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR91([NotNull] MonsterMessagesParser.R91Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r91"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR91([NotNull] MonsterMessagesParser.R91Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r96"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR96([NotNull] MonsterMessagesParser.R96Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r96"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR96([NotNull] MonsterMessagesParser.R96Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r105"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR105([NotNull] MonsterMessagesParser.R105Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r105"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR105([NotNull] MonsterMessagesParser.R105Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r49"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR49([NotNull] MonsterMessagesParser.R49Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r49"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR49([NotNull] MonsterMessagesParser.R49Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r29"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR29([NotNull] MonsterMessagesParser.R29Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r29"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR29([NotNull] MonsterMessagesParser.R29Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r117"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR117([NotNull] MonsterMessagesParser.R117Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r117"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR117([NotNull] MonsterMessagesParser.R117Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r76"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR76([NotNull] MonsterMessagesParser.R76Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r76"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR76([NotNull] MonsterMessagesParser.R76Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r114"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR114([NotNull] MonsterMessagesParser.R114Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r114"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR114([NotNull] MonsterMessagesParser.R114Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r73"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR73([NotNull] MonsterMessagesParser.R73Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r73"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR73([NotNull] MonsterMessagesParser.R73Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r54"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR54([NotNull] MonsterMessagesParser.R54Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r54"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR54([NotNull] MonsterMessagesParser.R54Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r8"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR8([NotNull] MonsterMessagesParser.R8Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r8"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR8([NotNull] MonsterMessagesParser.R8Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r63"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR63([NotNull] MonsterMessagesParser.R63Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r63"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR63([NotNull] MonsterMessagesParser.R63Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r102"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR102([NotNull] MonsterMessagesParser.R102Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r102"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR102([NotNull] MonsterMessagesParser.R102Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r41"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR41([NotNull] MonsterMessagesParser.R41Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r41"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR41([NotNull] MonsterMessagesParser.R41Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r28"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR28([NotNull] MonsterMessagesParser.R28Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r28"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR28([NotNull] MonsterMessagesParser.R28Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r121"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR121([NotNull] MonsterMessagesParser.R121Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r121"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR121([NotNull] MonsterMessagesParser.R121Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r7"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR7([NotNull] MonsterMessagesParser.R7Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r7"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR7([NotNull] MonsterMessagesParser.R7Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r23"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR23([NotNull] MonsterMessagesParser.R23Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r23"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR23([NotNull] MonsterMessagesParser.R23Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r59"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR59([NotNull] MonsterMessagesParser.R59Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r59"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR59([NotNull] MonsterMessagesParser.R59Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r92"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR92([NotNull] MonsterMessagesParser.R92Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r92"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR92([NotNull] MonsterMessagesParser.R92Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r70"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR70([NotNull] MonsterMessagesParser.R70Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r70"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR70([NotNull] MonsterMessagesParser.R70Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r57"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR57([NotNull] MonsterMessagesParser.R57Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r57"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR57([NotNull] MonsterMessagesParser.R57Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r119"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR119([NotNull] MonsterMessagesParser.R119Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r119"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR119([NotNull] MonsterMessagesParser.R119Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r77"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR77([NotNull] MonsterMessagesParser.R77Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r77"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR77([NotNull] MonsterMessagesParser.R77Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r87"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR87([NotNull] MonsterMessagesParser.R87Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r87"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR87([NotNull] MonsterMessagesParser.R87Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r85"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR85([NotNull] MonsterMessagesParser.R85Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r85"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR85([NotNull] MonsterMessagesParser.R85Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r43"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR43([NotNull] MonsterMessagesParser.R43Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r43"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR43([NotNull] MonsterMessagesParser.R43Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r90"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR90([NotNull] MonsterMessagesParser.R90Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r90"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR90([NotNull] MonsterMessagesParser.R90Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r50"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR50([NotNull] MonsterMessagesParser.R50Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r50"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR50([NotNull] MonsterMessagesParser.R50Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR3([NotNull] MonsterMessagesParser.R3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR3([NotNull] MonsterMessagesParser.R3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r88"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR88([NotNull] MonsterMessagesParser.R88Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r88"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR88([NotNull] MonsterMessagesParser.R88Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r107"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR107([NotNull] MonsterMessagesParser.R107Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r107"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR107([NotNull] MonsterMessagesParser.R107Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r36"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR36([NotNull] MonsterMessagesParser.R36Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r36"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR36([NotNull] MonsterMessagesParser.R36Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r97"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR97([NotNull] MonsterMessagesParser.R97Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r97"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR97([NotNull] MonsterMessagesParser.R97Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r13"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR13([NotNull] MonsterMessagesParser.R13Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r13"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR13([NotNull] MonsterMessagesParser.R13Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR2([NotNull] MonsterMessagesParser.R2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR2([NotNull] MonsterMessagesParser.R2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r120"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR120([NotNull] MonsterMessagesParser.R120Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r120"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR120([NotNull] MonsterMessagesParser.R120Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r14"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR14([NotNull] MonsterMessagesParser.R14Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r14"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR14([NotNull] MonsterMessagesParser.R14Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r18"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR18([NotNull] MonsterMessagesParser.R18Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r18"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR18([NotNull] MonsterMessagesParser.R18Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r75"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR75([NotNull] MonsterMessagesParser.R75Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r75"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR75([NotNull] MonsterMessagesParser.R75Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR1([NotNull] MonsterMessagesParser.R1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR1([NotNull] MonsterMessagesParser.R1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r81"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR81([NotNull] MonsterMessagesParser.R81Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r81"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR81([NotNull] MonsterMessagesParser.R81Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r9"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR9([NotNull] MonsterMessagesParser.R9Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r9"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR9([NotNull] MonsterMessagesParser.R9Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r111"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR111([NotNull] MonsterMessagesParser.R111Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r111"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR111([NotNull] MonsterMessagesParser.R111Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r38"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR38([NotNull] MonsterMessagesParser.R38Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r38"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR38([NotNull] MonsterMessagesParser.R38Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r21"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR21([NotNull] MonsterMessagesParser.R21Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r21"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR21([NotNull] MonsterMessagesParser.R21Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r22"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR22([NotNull] MonsterMessagesParser.R22Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r22"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR22([NotNull] MonsterMessagesParser.R22Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r72"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR72([NotNull] MonsterMessagesParser.R72Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r72"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR72([NotNull] MonsterMessagesParser.R72Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r62"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR62([NotNull] MonsterMessagesParser.R62Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r62"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR62([NotNull] MonsterMessagesParser.R62Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r125"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR125([NotNull] MonsterMessagesParser.R125Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r125"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR125([NotNull] MonsterMessagesParser.R125Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessage([NotNull] MonsterMessagesParser.MessageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessage([NotNull] MonsterMessagesParser.MessageContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
