//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MonsterMessages.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MonsterMessagesParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public interface IMonsterMessagesVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r34"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR34([NotNull] MonsterMessagesParser.R34Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r42"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR42([NotNull] MonsterMessagesParser.R42Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r115"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR115([NotNull] MonsterMessagesParser.R115Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r106"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR106([NotNull] MonsterMessagesParser.R106Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r71"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR71([NotNull] MonsterMessagesParser.R71Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r56"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR56([NotNull] MonsterMessagesParser.R56Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r10"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR10([NotNull] MonsterMessagesParser.R10Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r46"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR46([NotNull] MonsterMessagesParser.R46Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r20"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR20([NotNull] MonsterMessagesParser.R20Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r67"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR67([NotNull] MonsterMessagesParser.R67Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r78"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR78([NotNull] MonsterMessagesParser.R78Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r25"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR25([NotNull] MonsterMessagesParser.R25Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r74"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR74([NotNull] MonsterMessagesParser.R74Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r103"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR103([NotNull] MonsterMessagesParser.R103Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r94"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR94([NotNull] MonsterMessagesParser.R94Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r116"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR116([NotNull] MonsterMessagesParser.R116Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r60"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR60([NotNull] MonsterMessagesParser.R60Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR0([NotNull] MonsterMessagesParser.R0Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r110"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR110([NotNull] MonsterMessagesParser.R110Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r55"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR55([NotNull] MonsterMessagesParser.R55Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r100"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR100([NotNull] MonsterMessagesParser.R100Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r58"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR58([NotNull] MonsterMessagesParser.R58Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r61"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR61([NotNull] MonsterMessagesParser.R61Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r84"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR84([NotNull] MonsterMessagesParser.R84Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r65"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR65([NotNull] MonsterMessagesParser.R65Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR5([NotNull] MonsterMessagesParser.R5Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r112"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR112([NotNull] MonsterMessagesParser.R112Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r99"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR99([NotNull] MonsterMessagesParser.R99Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r39"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR39([NotNull] MonsterMessagesParser.R39Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r52"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR52([NotNull] MonsterMessagesParser.R52Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r47"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR47([NotNull] MonsterMessagesParser.R47Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r31"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR31([NotNull] MonsterMessagesParser.R31Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR4([NotNull] MonsterMessagesParser.R4Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r53"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR53([NotNull] MonsterMessagesParser.R53Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r124"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR124([NotNull] MonsterMessagesParser.R124Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r48"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR48([NotNull] MonsterMessagesParser.R48Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r123"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR123([NotNull] MonsterMessagesParser.R123Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r26"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR26([NotNull] MonsterMessagesParser.R26Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r51"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR51([NotNull] MonsterMessagesParser.R51Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR6([NotNull] MonsterMessagesParser.R6Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r122"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR122([NotNull] MonsterMessagesParser.R122Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r93"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR93([NotNull] MonsterMessagesParser.R93Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r37"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR37([NotNull] MonsterMessagesParser.R37Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r44"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR44([NotNull] MonsterMessagesParser.R44Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r12"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR12([NotNull] MonsterMessagesParser.R12Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r45"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR45([NotNull] MonsterMessagesParser.R45Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r19"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR19([NotNull] MonsterMessagesParser.R19Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r33"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR33([NotNull] MonsterMessagesParser.R33Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r108"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR108([NotNull] MonsterMessagesParser.R108Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r95"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR95([NotNull] MonsterMessagesParser.R95Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r82"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR82([NotNull] MonsterMessagesParser.R82Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r69"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR69([NotNull] MonsterMessagesParser.R69Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r104"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR104([NotNull] MonsterMessagesParser.R104Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r35"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR35([NotNull] MonsterMessagesParser.R35Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR32([NotNull] MonsterMessagesParser.R32Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r27"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR27([NotNull] MonsterMessagesParser.R27Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r40"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR40([NotNull] MonsterMessagesParser.R40Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r66"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR66([NotNull] MonsterMessagesParser.R66Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r101"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR101([NotNull] MonsterMessagesParser.R101Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r109"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR109([NotNull] MonsterMessagesParser.R109Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r80"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR80([NotNull] MonsterMessagesParser.R80Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r83"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR83([NotNull] MonsterMessagesParser.R83Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR64([NotNull] MonsterMessagesParser.R64Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r30"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR30([NotNull] MonsterMessagesParser.R30Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r17"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR17([NotNull] MonsterMessagesParser.R17Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r86"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR86([NotNull] MonsterMessagesParser.R86Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r15"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR15([NotNull] MonsterMessagesParser.R15Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r24"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR24([NotNull] MonsterMessagesParser.R24Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r11"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR11([NotNull] MonsterMessagesParser.R11Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r118"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR118([NotNull] MonsterMessagesParser.R118Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r98"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR98([NotNull] MonsterMessagesParser.R98Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR16([NotNull] MonsterMessagesParser.R16Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r89"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR89([NotNull] MonsterMessagesParser.R89Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r113"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR113([NotNull] MonsterMessagesParser.R113Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r126"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR126([NotNull] MonsterMessagesParser.R126Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r68"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR68([NotNull] MonsterMessagesParser.R68Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r79"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR79([NotNull] MonsterMessagesParser.R79Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r91"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR91([NotNull] MonsterMessagesParser.R91Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r96"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR96([NotNull] MonsterMessagesParser.R96Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r105"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR105([NotNull] MonsterMessagesParser.R105Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r49"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR49([NotNull] MonsterMessagesParser.R49Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r29"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR29([NotNull] MonsterMessagesParser.R29Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r117"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR117([NotNull] MonsterMessagesParser.R117Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r76"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR76([NotNull] MonsterMessagesParser.R76Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r114"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR114([NotNull] MonsterMessagesParser.R114Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r73"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR73([NotNull] MonsterMessagesParser.R73Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r54"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR54([NotNull] MonsterMessagesParser.R54Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR8([NotNull] MonsterMessagesParser.R8Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r63"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR63([NotNull] MonsterMessagesParser.R63Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r102"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR102([NotNull] MonsterMessagesParser.R102Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r41"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR41([NotNull] MonsterMessagesParser.R41Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r28"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR28([NotNull] MonsterMessagesParser.R28Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r121"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR121([NotNull] MonsterMessagesParser.R121Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r7"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR7([NotNull] MonsterMessagesParser.R7Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r23"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR23([NotNull] MonsterMessagesParser.R23Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r59"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR59([NotNull] MonsterMessagesParser.R59Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r92"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR92([NotNull] MonsterMessagesParser.R92Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r70"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR70([NotNull] MonsterMessagesParser.R70Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r57"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR57([NotNull] MonsterMessagesParser.R57Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r119"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR119([NotNull] MonsterMessagesParser.R119Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r77"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR77([NotNull] MonsterMessagesParser.R77Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r87"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR87([NotNull] MonsterMessagesParser.R87Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r85"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR85([NotNull] MonsterMessagesParser.R85Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r43"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR43([NotNull] MonsterMessagesParser.R43Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r90"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR90([NotNull] MonsterMessagesParser.R90Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r50"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR50([NotNull] MonsterMessagesParser.R50Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR3([NotNull] MonsterMessagesParser.R3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r88"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR88([NotNull] MonsterMessagesParser.R88Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r107"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR107([NotNull] MonsterMessagesParser.R107Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r36"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR36([NotNull] MonsterMessagesParser.R36Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r97"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR97([NotNull] MonsterMessagesParser.R97Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r13"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR13([NotNull] MonsterMessagesParser.R13Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR2([NotNull] MonsterMessagesParser.R2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r120"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR120([NotNull] MonsterMessagesParser.R120Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r14"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR14([NotNull] MonsterMessagesParser.R14Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r18"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR18([NotNull] MonsterMessagesParser.R18Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r75"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR75([NotNull] MonsterMessagesParser.R75Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR1([NotNull] MonsterMessagesParser.R1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r81"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR81([NotNull] MonsterMessagesParser.R81Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r9"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR9([NotNull] MonsterMessagesParser.R9Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r111"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR111([NotNull] MonsterMessagesParser.R111Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r38"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR38([NotNull] MonsterMessagesParser.R38Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r21"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR21([NotNull] MonsterMessagesParser.R21Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r22"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR22([NotNull] MonsterMessagesParser.R22Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r72"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR72([NotNull] MonsterMessagesParser.R72Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r62"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR62([NotNull] MonsterMessagesParser.R62Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.r125"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR125([NotNull] MonsterMessagesParser.R125Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MonsterMessagesParser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessage([NotNull] MonsterMessagesParser.MessageContext context);
}
