//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MonsterMessages.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MonsterMessagesParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public interface IMonsterMessagesListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r34"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR34([NotNull] MonsterMessagesParser.R34Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r34"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR34([NotNull] MonsterMessagesParser.R34Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r42"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR42([NotNull] MonsterMessagesParser.R42Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r42"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR42([NotNull] MonsterMessagesParser.R42Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r115"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR115([NotNull] MonsterMessagesParser.R115Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r115"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR115([NotNull] MonsterMessagesParser.R115Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r106"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR106([NotNull] MonsterMessagesParser.R106Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r106"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR106([NotNull] MonsterMessagesParser.R106Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r71"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR71([NotNull] MonsterMessagesParser.R71Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r71"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR71([NotNull] MonsterMessagesParser.R71Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r56"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR56([NotNull] MonsterMessagesParser.R56Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r56"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR56([NotNull] MonsterMessagesParser.R56Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r10"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR10([NotNull] MonsterMessagesParser.R10Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r10"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR10([NotNull] MonsterMessagesParser.R10Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r46"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR46([NotNull] MonsterMessagesParser.R46Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r46"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR46([NotNull] MonsterMessagesParser.R46Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r20"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR20([NotNull] MonsterMessagesParser.R20Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r20"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR20([NotNull] MonsterMessagesParser.R20Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r67"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR67([NotNull] MonsterMessagesParser.R67Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r67"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR67([NotNull] MonsterMessagesParser.R67Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r78"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR78([NotNull] MonsterMessagesParser.R78Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r78"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR78([NotNull] MonsterMessagesParser.R78Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r25"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR25([NotNull] MonsterMessagesParser.R25Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r25"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR25([NotNull] MonsterMessagesParser.R25Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r74"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR74([NotNull] MonsterMessagesParser.R74Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r74"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR74([NotNull] MonsterMessagesParser.R74Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r103"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR103([NotNull] MonsterMessagesParser.R103Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r103"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR103([NotNull] MonsterMessagesParser.R103Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r94"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR94([NotNull] MonsterMessagesParser.R94Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r94"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR94([NotNull] MonsterMessagesParser.R94Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r116"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR116([NotNull] MonsterMessagesParser.R116Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r116"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR116([NotNull] MonsterMessagesParser.R116Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r60"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR60([NotNull] MonsterMessagesParser.R60Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r60"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR60([NotNull] MonsterMessagesParser.R60Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR0([NotNull] MonsterMessagesParser.R0Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR0([NotNull] MonsterMessagesParser.R0Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r110"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR110([NotNull] MonsterMessagesParser.R110Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r110"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR110([NotNull] MonsterMessagesParser.R110Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r55"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR55([NotNull] MonsterMessagesParser.R55Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r55"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR55([NotNull] MonsterMessagesParser.R55Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r100"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR100([NotNull] MonsterMessagesParser.R100Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r100"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR100([NotNull] MonsterMessagesParser.R100Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r58"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR58([NotNull] MonsterMessagesParser.R58Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r58"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR58([NotNull] MonsterMessagesParser.R58Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r61"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR61([NotNull] MonsterMessagesParser.R61Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r61"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR61([NotNull] MonsterMessagesParser.R61Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r84"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR84([NotNull] MonsterMessagesParser.R84Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r84"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR84([NotNull] MonsterMessagesParser.R84Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r65"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR65([NotNull] MonsterMessagesParser.R65Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r65"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR65([NotNull] MonsterMessagesParser.R65Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR5([NotNull] MonsterMessagesParser.R5Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR5([NotNull] MonsterMessagesParser.R5Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r112"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR112([NotNull] MonsterMessagesParser.R112Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r112"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR112([NotNull] MonsterMessagesParser.R112Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r99"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR99([NotNull] MonsterMessagesParser.R99Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r99"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR99([NotNull] MonsterMessagesParser.R99Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r39"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR39([NotNull] MonsterMessagesParser.R39Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r39"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR39([NotNull] MonsterMessagesParser.R39Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r52"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR52([NotNull] MonsterMessagesParser.R52Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r52"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR52([NotNull] MonsterMessagesParser.R52Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r47"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR47([NotNull] MonsterMessagesParser.R47Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r47"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR47([NotNull] MonsterMessagesParser.R47Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r31"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR31([NotNull] MonsterMessagesParser.R31Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r31"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR31([NotNull] MonsterMessagesParser.R31Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR4([NotNull] MonsterMessagesParser.R4Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR4([NotNull] MonsterMessagesParser.R4Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r53"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR53([NotNull] MonsterMessagesParser.R53Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r53"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR53([NotNull] MonsterMessagesParser.R53Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r124"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR124([NotNull] MonsterMessagesParser.R124Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r124"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR124([NotNull] MonsterMessagesParser.R124Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r48"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR48([NotNull] MonsterMessagesParser.R48Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r48"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR48([NotNull] MonsterMessagesParser.R48Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r123"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR123([NotNull] MonsterMessagesParser.R123Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r123"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR123([NotNull] MonsterMessagesParser.R123Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r26"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR26([NotNull] MonsterMessagesParser.R26Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r26"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR26([NotNull] MonsterMessagesParser.R26Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r51"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR51([NotNull] MonsterMessagesParser.R51Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r51"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR51([NotNull] MonsterMessagesParser.R51Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR6([NotNull] MonsterMessagesParser.R6Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR6([NotNull] MonsterMessagesParser.R6Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r122"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR122([NotNull] MonsterMessagesParser.R122Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r122"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR122([NotNull] MonsterMessagesParser.R122Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r93"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR93([NotNull] MonsterMessagesParser.R93Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r93"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR93([NotNull] MonsterMessagesParser.R93Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r37"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR37([NotNull] MonsterMessagesParser.R37Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r37"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR37([NotNull] MonsterMessagesParser.R37Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r44"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR44([NotNull] MonsterMessagesParser.R44Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r44"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR44([NotNull] MonsterMessagesParser.R44Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r12"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR12([NotNull] MonsterMessagesParser.R12Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r12"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR12([NotNull] MonsterMessagesParser.R12Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r45"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR45([NotNull] MonsterMessagesParser.R45Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r45"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR45([NotNull] MonsterMessagesParser.R45Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r19"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR19([NotNull] MonsterMessagesParser.R19Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r19"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR19([NotNull] MonsterMessagesParser.R19Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r33"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR33([NotNull] MonsterMessagesParser.R33Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r33"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR33([NotNull] MonsterMessagesParser.R33Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r108"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR108([NotNull] MonsterMessagesParser.R108Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r108"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR108([NotNull] MonsterMessagesParser.R108Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r95"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR95([NotNull] MonsterMessagesParser.R95Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r95"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR95([NotNull] MonsterMessagesParser.R95Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r82"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR82([NotNull] MonsterMessagesParser.R82Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r82"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR82([NotNull] MonsterMessagesParser.R82Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r69"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR69([NotNull] MonsterMessagesParser.R69Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r69"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR69([NotNull] MonsterMessagesParser.R69Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r104"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR104([NotNull] MonsterMessagesParser.R104Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r104"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR104([NotNull] MonsterMessagesParser.R104Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r35"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR35([NotNull] MonsterMessagesParser.R35Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r35"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR35([NotNull] MonsterMessagesParser.R35Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR32([NotNull] MonsterMessagesParser.R32Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR32([NotNull] MonsterMessagesParser.R32Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r27"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR27([NotNull] MonsterMessagesParser.R27Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r27"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR27([NotNull] MonsterMessagesParser.R27Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r40"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR40([NotNull] MonsterMessagesParser.R40Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r40"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR40([NotNull] MonsterMessagesParser.R40Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r66"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR66([NotNull] MonsterMessagesParser.R66Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r66"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR66([NotNull] MonsterMessagesParser.R66Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r101"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR101([NotNull] MonsterMessagesParser.R101Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r101"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR101([NotNull] MonsterMessagesParser.R101Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r109"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR109([NotNull] MonsterMessagesParser.R109Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r109"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR109([NotNull] MonsterMessagesParser.R109Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r80"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR80([NotNull] MonsterMessagesParser.R80Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r80"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR80([NotNull] MonsterMessagesParser.R80Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r83"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR83([NotNull] MonsterMessagesParser.R83Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r83"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR83([NotNull] MonsterMessagesParser.R83Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR64([NotNull] MonsterMessagesParser.R64Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR64([NotNull] MonsterMessagesParser.R64Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r30"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR30([NotNull] MonsterMessagesParser.R30Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r30"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR30([NotNull] MonsterMessagesParser.R30Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r17"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR17([NotNull] MonsterMessagesParser.R17Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r17"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR17([NotNull] MonsterMessagesParser.R17Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r86"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR86([NotNull] MonsterMessagesParser.R86Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r86"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR86([NotNull] MonsterMessagesParser.R86Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r15"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR15([NotNull] MonsterMessagesParser.R15Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r15"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR15([NotNull] MonsterMessagesParser.R15Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r24"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR24([NotNull] MonsterMessagesParser.R24Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r24"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR24([NotNull] MonsterMessagesParser.R24Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r11"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR11([NotNull] MonsterMessagesParser.R11Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r11"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR11([NotNull] MonsterMessagesParser.R11Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r118"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR118([NotNull] MonsterMessagesParser.R118Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r118"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR118([NotNull] MonsterMessagesParser.R118Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r98"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR98([NotNull] MonsterMessagesParser.R98Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r98"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR98([NotNull] MonsterMessagesParser.R98Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR16([NotNull] MonsterMessagesParser.R16Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR16([NotNull] MonsterMessagesParser.R16Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r89"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR89([NotNull] MonsterMessagesParser.R89Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r89"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR89([NotNull] MonsterMessagesParser.R89Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r113"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR113([NotNull] MonsterMessagesParser.R113Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r113"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR113([NotNull] MonsterMessagesParser.R113Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r126"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR126([NotNull] MonsterMessagesParser.R126Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r126"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR126([NotNull] MonsterMessagesParser.R126Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r68"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR68([NotNull] MonsterMessagesParser.R68Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r68"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR68([NotNull] MonsterMessagesParser.R68Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r79"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR79([NotNull] MonsterMessagesParser.R79Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r79"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR79([NotNull] MonsterMessagesParser.R79Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r91"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR91([NotNull] MonsterMessagesParser.R91Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r91"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR91([NotNull] MonsterMessagesParser.R91Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r96"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR96([NotNull] MonsterMessagesParser.R96Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r96"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR96([NotNull] MonsterMessagesParser.R96Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r105"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR105([NotNull] MonsterMessagesParser.R105Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r105"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR105([NotNull] MonsterMessagesParser.R105Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r49"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR49([NotNull] MonsterMessagesParser.R49Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r49"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR49([NotNull] MonsterMessagesParser.R49Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r29"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR29([NotNull] MonsterMessagesParser.R29Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r29"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR29([NotNull] MonsterMessagesParser.R29Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r117"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR117([NotNull] MonsterMessagesParser.R117Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r117"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR117([NotNull] MonsterMessagesParser.R117Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r76"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR76([NotNull] MonsterMessagesParser.R76Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r76"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR76([NotNull] MonsterMessagesParser.R76Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r114"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR114([NotNull] MonsterMessagesParser.R114Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r114"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR114([NotNull] MonsterMessagesParser.R114Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r73"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR73([NotNull] MonsterMessagesParser.R73Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r73"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR73([NotNull] MonsterMessagesParser.R73Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r54"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR54([NotNull] MonsterMessagesParser.R54Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r54"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR54([NotNull] MonsterMessagesParser.R54Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR8([NotNull] MonsterMessagesParser.R8Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR8([NotNull] MonsterMessagesParser.R8Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r63"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR63([NotNull] MonsterMessagesParser.R63Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r63"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR63([NotNull] MonsterMessagesParser.R63Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r102"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR102([NotNull] MonsterMessagesParser.R102Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r102"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR102([NotNull] MonsterMessagesParser.R102Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r41"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR41([NotNull] MonsterMessagesParser.R41Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r41"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR41([NotNull] MonsterMessagesParser.R41Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r28"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR28([NotNull] MonsterMessagesParser.R28Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r28"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR28([NotNull] MonsterMessagesParser.R28Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r121"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR121([NotNull] MonsterMessagesParser.R121Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r121"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR121([NotNull] MonsterMessagesParser.R121Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r7"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR7([NotNull] MonsterMessagesParser.R7Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r7"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR7([NotNull] MonsterMessagesParser.R7Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r23"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR23([NotNull] MonsterMessagesParser.R23Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r23"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR23([NotNull] MonsterMessagesParser.R23Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r59"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR59([NotNull] MonsterMessagesParser.R59Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r59"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR59([NotNull] MonsterMessagesParser.R59Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r92"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR92([NotNull] MonsterMessagesParser.R92Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r92"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR92([NotNull] MonsterMessagesParser.R92Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r70"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR70([NotNull] MonsterMessagesParser.R70Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r70"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR70([NotNull] MonsterMessagesParser.R70Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r57"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR57([NotNull] MonsterMessagesParser.R57Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r57"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR57([NotNull] MonsterMessagesParser.R57Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r119"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR119([NotNull] MonsterMessagesParser.R119Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r119"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR119([NotNull] MonsterMessagesParser.R119Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r77"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR77([NotNull] MonsterMessagesParser.R77Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r77"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR77([NotNull] MonsterMessagesParser.R77Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r87"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR87([NotNull] MonsterMessagesParser.R87Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r87"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR87([NotNull] MonsterMessagesParser.R87Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r85"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR85([NotNull] MonsterMessagesParser.R85Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r85"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR85([NotNull] MonsterMessagesParser.R85Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r43"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR43([NotNull] MonsterMessagesParser.R43Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r43"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR43([NotNull] MonsterMessagesParser.R43Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r90"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR90([NotNull] MonsterMessagesParser.R90Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r90"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR90([NotNull] MonsterMessagesParser.R90Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r50"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR50([NotNull] MonsterMessagesParser.R50Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r50"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR50([NotNull] MonsterMessagesParser.R50Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR3([NotNull] MonsterMessagesParser.R3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR3([NotNull] MonsterMessagesParser.R3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r88"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR88([NotNull] MonsterMessagesParser.R88Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r88"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR88([NotNull] MonsterMessagesParser.R88Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r107"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR107([NotNull] MonsterMessagesParser.R107Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r107"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR107([NotNull] MonsterMessagesParser.R107Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r36"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR36([NotNull] MonsterMessagesParser.R36Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r36"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR36([NotNull] MonsterMessagesParser.R36Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r97"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR97([NotNull] MonsterMessagesParser.R97Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r97"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR97([NotNull] MonsterMessagesParser.R97Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r13"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR13([NotNull] MonsterMessagesParser.R13Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r13"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR13([NotNull] MonsterMessagesParser.R13Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR2([NotNull] MonsterMessagesParser.R2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR2([NotNull] MonsterMessagesParser.R2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r120"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR120([NotNull] MonsterMessagesParser.R120Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r120"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR120([NotNull] MonsterMessagesParser.R120Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r14"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR14([NotNull] MonsterMessagesParser.R14Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r14"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR14([NotNull] MonsterMessagesParser.R14Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r18"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR18([NotNull] MonsterMessagesParser.R18Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r18"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR18([NotNull] MonsterMessagesParser.R18Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r75"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR75([NotNull] MonsterMessagesParser.R75Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r75"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR75([NotNull] MonsterMessagesParser.R75Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR1([NotNull] MonsterMessagesParser.R1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR1([NotNull] MonsterMessagesParser.R1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r81"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR81([NotNull] MonsterMessagesParser.R81Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r81"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR81([NotNull] MonsterMessagesParser.R81Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r9"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR9([NotNull] MonsterMessagesParser.R9Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r9"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR9([NotNull] MonsterMessagesParser.R9Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r111"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR111([NotNull] MonsterMessagesParser.R111Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r111"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR111([NotNull] MonsterMessagesParser.R111Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r38"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR38([NotNull] MonsterMessagesParser.R38Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r38"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR38([NotNull] MonsterMessagesParser.R38Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r21"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR21([NotNull] MonsterMessagesParser.R21Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r21"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR21([NotNull] MonsterMessagesParser.R21Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r22"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR22([NotNull] MonsterMessagesParser.R22Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r22"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR22([NotNull] MonsterMessagesParser.R22Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r72"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR72([NotNull] MonsterMessagesParser.R72Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r72"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR72([NotNull] MonsterMessagesParser.R72Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r62"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR62([NotNull] MonsterMessagesParser.R62Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r62"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR62([NotNull] MonsterMessagesParser.R62Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.r125"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR125([NotNull] MonsterMessagesParser.R125Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.r125"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR125([NotNull] MonsterMessagesParser.R125Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MonsterMessagesParser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessage([NotNull] MonsterMessagesParser.MessageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MonsterMessagesParser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessage([NotNull] MonsterMessagesParser.MessageContext context);
}
